# Generated by Django 3.2.5 on 2021-07-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signUpView', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
