# Generated by Django 3.2.5 on 2021-07-23 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepreferences',
            name='profile_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
